### ISSUE TITLE
Api application/json vs application/vnd.api+json

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/crud-json-api#9] opened 2017-06-22 09:14 UTC
With most default baked apps it responds differently for the two above.
This can lead to inconsistent and confusing output - differently formatted depending on the request type.

We should document this, and also recommend to only allow one format, e.g. the jsonapi one then:
```php
public function beforeFilter(Event $event)
        // do not render out the now inconsistent one for is(json)
        if (!$this->request->is('jsonapi')) {
            throw new NotFoundException('Invalid access, use application/vnd.api+json for Content-Type and Accept.');
        }
}
```

**Comment by bravo-kernel** [comment] 2017-06-22 11:39
Are you talking about a change to the bake templates or a change to the listener?

In case of the latter I agree this could be documented better. The behavior however, is by design (unless I am missing some bug here): one should in theory be able to load multiple listeners, only the one matching a specific header should kick in. [Hence:](https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Listener/JsonApiListener.php#L77)

```php
        // make sure the listener does absolutely nothing unless
        // the application/vnd.api+json Accept header is used.
        if (!$this->_checkRequestType('jsonapi')) {
            return null;
        }
```

Discussed with @jippi a long time ago when starting work on the listener. https://github.com/FriendsOfCake/crud/pull/445#discussion_r80375440

I hope I am not misunderstanding you, trying to be as informative as possible here, appreciate your input (and eyes looking at the code) 👍

**Comment by dereuromark** [comment] 2017-06-22 13:28
No, what I mean is that by default for most apps it will accept both normal .json via browser and the header based jsonapi one.
But only for the latter it will output the expected format, for json the normal crud stuff will be returned.
All APIs however would not find this magic switch acceptable, we should at least note that this can be deactivated by the above snippet etc.
Some might not be aware of the dual-output and will run into similar confusions.

**Comment by ADmad** [comment] 2017-06-22 13:40
I highly doubt someone would be using mix of `application/json` and `application/vnd.api+json` for his/hee API. Also `.json` extension will be recognized only if you turn on extension routing which I doubt anyone using json-api would do for his/her API routes. So unless I am misunderstanding what you are saying I don't see any chance of confusion.

**Comment by dereuromark** [comment] 2017-06-22 13:43
A default baked app has all those included.
Thats why I am saying this - it is by default an issue we should and need to address :)

**Comment by ADmad** [comment] 2017-06-22 13:54
If a default baked app has `.json` extension routing turn on by default then it's a bad default which should be removed.

**Comment by dereuromark** [comment] 2017-06-22 13:59
They also contain the auto-magic json parsing (incl the baked controller serialize per action) :)
https://github.com/cakephp/app/blob/master/src/Controller/AppController.php#L63-L67
Which is then part of the issue I was explaining here - either we clearly say to replace with json API, or we must make sure they cannot accidentally be used together (only deliberately).

**Comment by ADmad** [comment] 2017-06-22 14:02
That line checks for `'application/json` not `application/vnd.api+json` for which this plugin responds to so how is there cause for confusion?

**Comment by dereuromark** [comment] 2017-06-22 14:04
because that causes the above issue. it will be able to load one format with browser access for json, the other with header based e.g. postman access for jsonapi. those are then two different listeners/renderers switching magically between each other based on the header being present or not, without the end user being informed or clear about this.

**Comment by dereuromark** [comment] 2017-06-22 14:05
Thus my docs recommendation of 
```php
public function beforeFilter(Event $event)
        // do not render out the now inconsistent one for is(json)
        if (!$this->request->is('jsonapi')) {
            throw new NotFoundException('Invalid access, use application/vnd.api+json for Content-Type and Accept.');
        }
}
```
to specifically only whitelist the desired jsonapi for the general use case.

**Comment by ADmad** [comment] 2017-06-22 14:13
This plugin's listener won't do anything if request is not of type `application/vnd.api+json`. Let the user have `.json` extension routing or other code to handle requests for `application/json`. There's no need for us to explicitly try to prevent that.

I'll leave it to @bravo-kernel and @dakota who are mainly involved with the plugin's development to decide.

**Comment by dereuromark** [comment] 2017-06-22 14:14
;) All right.
If no one sees any improvements or clarifications in docs here, you guys can close.

**Comment by bravo-kernel** [comment] 2017-06-24 12:16
I recall some previous confusion where people were testing crud-json-api from the browser and not seeing the expected results (obviously). I will follow-up on this issue once I have found some time.

**Comment by bravo-kernel** [comment] 2017-09-16 20:33
Closing as I think this should not be solved in crud-json-api.

**Closed as completed by bravo-kernel** 2017-09-16 20:33 UTC

**Comment by hrueben** [comment] 2020-06-11 06:05
#9 regards to my wife #1 who's doing to much :-) just tried of this life ur makn it difficult R&Y belongs to getther you are very good at what you do.ur a very smart guy .please stop Bean a bully picking on me..200. U know I can't read and understand I'm trying dam thug.
