### ISSUE TITLE
formatResults 

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud-json-api#87] opened 2018-09-04 17:34 UTC
Not work when 

```
public function findSaldo(Query $query, array $options = []) {
        $query->formatResults(function (\Cake\Collection\CollectionInterface $results) use ($options) {
            return $results->map(function ($row) {
                return $row['teste'] = 1;
            });
        });

        return $query;
    }

```

error:  - Trying to clone an uncloneable object of class Cake\Datasource\ResultSetDecorator

**Comment by josegonzalez** [comment] 2018-09-05 23:55
Can you show the full trace output of this, as well as the code that you are using to invoke this find?

**Comment by thiagoreri** [comment] 2018-09-06 14:30
Controller
```
public function index() {
        try {
            $this->Crud->action()->findMethod('list');

            return $this->Crud->execute();
        } catch (\Exception $e) {
            throw new InternalErrorException($e->getMessage());
        }
    }

```
Model
```
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\Table;

class ContaFinanceiraTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('conta_financeira');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
        $this->setEntityClass('ContaFinanceira');
        
        $this->addBehavior('Search.Search');

        $this->belongsTo('Empresa', [
            'foreignKey' => 'empresa_id',
            'joinType' => 'INNER',
            'propertyName' => 'empresa'
        ]);
        $this->belongsTo('Usuario', [
            'foreignKey' => 'usuario_id',
            'joinType' => 'INNER',
            'propertyName' => 'usuario'
        ]);
        $this->belongsTo('Banco', [
            'foreignKey' => 'banco_id',
            'joinType' => 'INNER',
            'propertyName' => 'banco'
        ]);
    }
    
    public function findList(Query $query, array $options = [])  {
        $query->formatResults(function (\Cake\Collection\CollectionInterface $results) {
            return $results->map(function ($row) {
                $row['test'] = 'test';
                return $row;
            });
        });

        return $query;
    }
}

```

**Comment by thiagoreri** [comment] 2018-09-06 14:31
Trying to clone an uncloneable object of class Cake\Datasource\ResultSetDecorator

**Comment by thiagoreri** [comment] 2018-09-06 14:33
How show the full trace?

**Comment by Graziel** [comment] 2018-12-22 05:37
ive same problem, updated from 4.4.2 to 5.4.6 and my table has `translate` behavior https://github.com/cakephp/cakephp/blob/0be30d0c02cf955e58fedb2d47d8264e38342820/src/ORM/Behavior/TranslateBehavior.php#L262
```
2018-12-22 05:13:36 Error: [Error] Trying to clone an uncloneable object of class Cake\Datasource\ResultSetDecorator
#0 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud-json-api/src/Listener/JsonApiListener.php(826): CrudJsonApi\Listener\JsonApiListener->_deduplicateResultSet(Object(Crud\Event\Subject))
#1 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud-json-api/src/Listener/JsonApiListener.php(709): CrudJsonApi\Listener\JsonApiListener->_getFindResult(Object(Crud\Event\Subject))
#2 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud-json-api/src/Listener/JsonApiListener.php(647): CrudJsonApi\Listener\JsonApiListener->_renderWithResources(Object(Crud\Event\Subject))
#3 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Listener/ApiListener.php(129): CrudJsonApi\Listener\JsonApiListener->render(Object(Crud\Event\Subject))
#4 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Event/EventManager.php(353): Crud\Listener\ApiListener->respond(Object(Cake\Event\Event))
#5 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Event/EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#6 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(540): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#7 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Core/ProxyTrait.php(38): Crud\Controller\Component\CrudComponent->trigger('Crud.beforeRend...', Object(Crud\Event\Subject))
#8 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Action/IndexAction.php(61): Crud\Core\BaseObject->_trigger('beforeRender', Object(Crud\Event\Subject))
#9 [internal function]: Crud\Action\IndexAction->_handle()
#10 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Action/BaseAction.php(71): call_user_func_array(Array, Array)
#11 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(244): Crud\Action\BaseAction->handle(Array)
#12 /home/vagrant/Apps/test.app/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php(68): Crud\Controller\Component\CrudComponent->execute()
#13 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): App\Controller\Backend\AppController->invokeAction()
#14 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\Backend\LanguagesController))
#15 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 /home/vagrant/Apps/test.app/src/Middleware/LocaleSelectorMiddleware.php(65): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocaleSelectorMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 /home/vagrant/Apps/test.app/src/Middleware/CorsMiddleware.php(34): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\CorsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#25 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#26 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#27 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php(197): Cake\Http\Server->run(Object(Cake\Http\ServerRequest))
#30 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php(516): Cake\TestSuite\MiddlewareDispatcher->execute(Array)
#31 /home/vagrant/Apps/test.app/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php(396): Cake\TestSuite\IntegrationTestCase->_sendRequest('/backend/langua...', 'GET')
#32 /home/vagrant/Apps/test.app/tests/TestCase/Controller/Backend/LanguagesControllerTest.php(17): Cake\TestSuite\IntegrationTestCase->get(Array)
#33 [internal function]: App\Test\TestCase\Controller\Backend\LanguagesControllerTest->testIndex()
#34 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1071): ReflectionMethod->invokeArgs(Object(App\Test\TestCase\Controller\Backend\LanguagesControllerTest), Array)
#35 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/Framework/TestCase.php(939): PHPUnit\Framework\TestCase->runTest()
#36 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/Framework/TestResult.php(698): PHPUnit\Framework\TestCase->runBare()
#37 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(App\Test\TestCase\Controller\Backend\LanguagesControllerTest))
#38 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#39 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#40 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#41 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#42 /home/vagrant/Apps/test.app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#43 {main}
Request URL: /backend/languages?lang=pl
```

**Comment by dakota** [comment] 2019-03-19 11:01
To expand on this.

The problem is with https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Listener/JsonApiListener.php#L797

When calling `formatResults()` on a query object, the resulting results object is a `ResultSetDecorator` instead of a `ResultSet`. `ResultSetDecorator` is a unclonable object, which causes the noted error.

**Comment by dakota** [comment] 2020-09-08 13:45
This has been fixed in recent versions.

**Closed as completed by dakota** 2020-09-08 13:45 UTC
